networks:
  traefik:
    external: true
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    command:
      # Enables the web UI and tells Traefik to listen to docker
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.traefikresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.traefikresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.traefikresolver.acme.tlschallenge=true"
    ports:
      - 80:80
      - 443:443
      # The Web UI (enabled by --api.insecure=true)
      - 880:8080
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
