networks:
  flowise:
    external: true
  traefik:
    external: true
services:
  flowise:
    image: flowiseai/flowise:1.6.2
    container_name: flowise
    restart: always
    environment:
      - FLOWISE_USERNAME=${FLOWISE_USERNAME}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
    ports:
      - 3000:3000
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.flowise.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.flowise.entrypoints=websecure
      - traefik.http.routers.flowise.tls=true
      - traefik.http.routers.flowise.tls.certresolver=traefikresolver
    volumes:
      - ./flowise_data:/root/.flowise
    command: /bin/sh -c "sleep 3; flowise start"
    networks:
      - traefik
      - flowise
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-stack
    restart: always
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    ports:
      - 6379:6379
    networks:
      - flowise
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    restart: always
    command: "--workers 1 --host 0.0.0.0 --port 8000 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"
    volumes:
      - ./chroma-data:/chroma/chroma
    ports:
      - 8000:8000
    networks:
      - flowise
    healthcheck:
      # Adjust below to match your container port
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.1
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    ports:
      - 8080:8080
      - 50051:50051
    networks:
      - flowise
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    restart: always
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: "text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai"
      CLUSTER_HOSTNAME: "node1"
